import streamlit as st
import replicate
import google.generativeai as genai
from PIL import Image
import io

# --- 1. 页面配置 ---
st.set_page_config(page_title="视觉工场", page_icon="🎨", layout="wide")

# 自定义样式
st.markdown("""
<style>
    .stButton button {width: 100%;}
    .stImage {border-radius: 10px;}
</style>
""", unsafe_allow_html=True)

# --- 2. 验证 Keys ---
if "REPLICATE_API_TOKEN" not in st.secrets:
    st.error("❌ 未找到 Replicate API Token，请在 Secrets 中配置！")
    st.stop()
if "GOOGLE_API_KEY" not in st.secrets:
    st.warning("⚠️ 未找到 Google API Key，智能优化提示词功能将不可用。")
else:
    genai.configure(api_key=st.secrets["GOOGLE_API_KEY"])

# --- 3. 侧边栏配置 ---
with st.sidebar:
    st.title("🎨 绘图参数设置")
    
    # 模型选择 (FLUX 1.1 Pro 是目前最强最快的)
    model_version = "black-forest-labs/flux-1.1-pro"
    
    aspect_ratio = st.selectbox(
        "图片比例 (Aspect Ratio)",
        ["1:1 (电商主图)", "16:9 (Banner/海报)", "9:16 (TikTok/Reels)", "4:3", "3:2"]
    )
    
    output_format = st.selectbox("输出格式", ["webp", "jpg", "png"])
    safety_tolerance = st.slider("安全过滤等级 (越低越严)", 1, 5, 2)

# --- 4. 核心逻辑 ---
st.title("🎨 AI 视觉工场 (Visual Studio)")
st.caption("Powered by FLUX.1 Pro + Gemini 3.0 Brain")

col1, col2 = st.columns([4, 6])

with col1:
    st.subheader("1. 创意输入")
    
    # A. 基础输入
    raw_prompt = st.text_area(
        "描述你想要的画面 (支持中文)", 
        placeholder="例如：一个白色的陶瓷咖啡杯放在木质桌面上，旁边有咖啡豆，清晨阳光，高分辨率...",
        height=100
    )
    
    # B. 智能优化按钮 (Gemini)
    if st.button("✨ 用 Gemini 优化提示词 (变专业)", type="secondary"):
        if not raw_prompt:
            st.warning("请先输入一些简单的描述！")
        else:
            with st.spinner("Gemini 正在构思光影和构图..."):
                try:
                    # 调用 Gemini 润色
                    g_model = genai.GenerativeModel('gemini-3-pro-preview') # 或者 gemini-1.5-pro
                    g_prompt = f"""
                    你是一个专业的AI绘图提示词工程师 (Prompt Engineer)。
                    请把用户的这个简单描述："{raw_prompt}"
                    改写成一个 FLUX 模型能听懂的、高质量的英文 Prompt。
                    
                    要求：
                    1. 增加光影、材质、镜头参数（如 8k, photorealistic, cinematic lighting）。
                    2. 如果用户提到了产品上的文字，请用双引号明确标注，例如 text "COFFEE"。
                    3. 直接输出英文 Prompt，不要任何解释。
                    """
                    response = g_model.generate_content(g_prompt)
                    optimized_prompt = response.text
                    
                    # 存入 Session State 以便显示
                    st.session_state['final_prompt'] = optimized_prompt
                    st.success("优化完成！已自动填入下方。")
                except Exception as e:
                    st.error(f"Gemini 优化失败: {e}")

    # C. 最终提示词 (发送给 FLUX 的)
    # 如果 Session 中有优化过的词，就用优化过的，否则用原本的
    default_prompt = st.session_state.get('final_prompt', raw_prompt)
    final_prompt = st.text_area(
        "最终英文 Prompt (可手动微调)", 
        value=default_prompt,
        height=150,
        help="这是实际发送给绘图模型的指令，必须是英文。"
    )

with col2:
    st.subheader("2. 生成结果")
    
    generate_btn = st.button("🚀 开始绘图 (Run FLUX)", type="primary")
    
    if generate_btn:
        if not final_prompt:
            st.warning("提示词不能为空！")
        else:
            with st.spinner("🎨 FLUX 正在渲染像素... (约需 5-10秒)"):
                try:
                    # 调用 Replicate
                    output = replicate.run(
                        model_version,
                        input={
                            "prompt": final_prompt,
                            "aspect_ratio": aspect_ratio.split(" ")[0], # 提取 1:1
                            "output_format": output_format,
                            "output_quality": 90,
                            "safety_tolerance": safety_tolerance
                        }
                    )
                    
                    # FLUX 1.1 Pro 返回的是一个文件流对象或 URL
                    # 通常 output 就是一个 image url
                    image_url = str(output)
                    
                    st.image(image_url, caption="Generated by FLUX.1 Pro", use_column_width=True)
                    st.success("✅ 生成成功！右键可另存为图片。")
                    
                    # 显示下载链接
                    st.markdown(f"[📥 点击下载原图]({image_url})")
                    
                except Exception as e:
                    st.error(f"绘图失败: {e}")
                    st.info("💡 提示：请检查 Replicate 余额或 API Token 是否正确。")

st.markdown("---")
st.info("💡 小技巧：如果你想在产品上印字，请在提示词里写：text \"YOUR TEXT\"")
